<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="S5Wrapper" targetNamespace="http://enterprise.netbeans.org/bpel/S5Wrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/S5Wrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://ce.uniroma2.it">
    <import location="http://partner:8084/axis2/services/S5?wsdl" namespace="http://ce.uniroma2.it"/>
    <plnk:partnerLinkType name="S5LinkType">
        <plnk:role name="S5Role" portType="ns:S5PortType"/>
    </plnk:partnerLinkType>
</definitions>

