% SCRIPT compose_aggre
%
% this is the main MATLAB script. It is invoked within the Matlabtool class to compute the 
% solution for the per-flow optimization policy
% 
% compose_aggre takes the problem input indirectly by executing the script "travel_planner_all". 
% The latter, which is automatically generated by the Optimization Engine, defines the MATLAB data
% structures required for the problem solution, including the the workflow description, the SLA and 
% the concrete service parameters. 


% the main workflow data structure, the array 'node', requires global scope 

global node

% read workflow description, SLA and concrete service. This script is generated by the Matlabtool class 
% whenever solution of the per-flow optimization policy is required

travel_planner_all

% find fork/join nodes

build(1:N,classe,root,sink,N+1);

% compute requests rate for the different service class

node(N+1).lambda=gamma;
calcola_l(N+1,gamma,gamma);

% build the PL problem matrices

build_problem_eq_red;

% compute Q_min/max of the different performance indices (Required for normalization)

calcola_min_max_aggre;

% compute obejctive function

calcola_costi_aggre_red;

% problem solution

calcola_soluzione_aggre;
